project:
  type: book
  # type: website
  output-dir: docs

book:
  title: "NTL Research Protocols"
  author: "NTL-LTER"
  date: "6/29/2023"
  site-url: https://hdugan.github.io/NTLprotocols/
  repo-url: https://github.com/hdugan/NTLprotocols/
  chapters:
    - index.qmd
    - part: fieldProtocols.qmd
      chapters:
        - benthicMacroinvertebrates.qmd
    - part: biologicalProtocols.qmd
      chapters:
        - phytoplankton.qmd
        - zooplankton.qmd
    - part: waterChem.qmd
      chapters:
        - alkalinity.qmd


#bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - journal.scss
    author-meta: "Hilary Dugan"
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    colorlinks: true
    
editor: visual

