# Alkalinity {#sec-alkalinity}

Revised: Grace Wilkinson, March 2023

### Purpose:

This procedure describes the steps to potentiometrically titrate water samples with standardized hydrochloric acid to calculate alkalinity according to Andersen, 2002 and USGS National Field Manual for the Collection of Water-Quality Data. The units of alkalinity for this analysis are microequivalents of carbonate per liter.

### Sample Holding Time:

≤ 14 days \@ 4° C unpreserved

### Materials Required for Titration

(see materials for regents in step 5):

-   MilliQ water
-   0.05N Hydrochloric Acid
-   1000 ueq/L Sodium Carbonate standard
-   pH meter and probe
-   pH buffers
-   Analytical balance
-   P200 manual, adjustable pipette
-   P100 electronic, adjustable pipette
-   Pipet tips
-   Small, graduated cups for titration
-   Micro-stirbar
-   MilliQ squirt bottle
-   Kimwipes

### Glassware Preparation:

The glass jar to hold waste rinses and the graduated cups used for titration should be rinsed with DI water from the tap at the sink and set upside down to dry.

### Personal Protective Equipment / Waste Disposal:

Nitrile gloves and eye protection should be worn while titrating. Always use chemical resistant gloves (not latex), safety glasses, lab coat, and a fume hood while using concentrated acids to prepare the 0.05N HCl. This is not only for your protection, but also to prevent contamination of samples. Proper personal protective equipment is always required for safety and contamination prevention.

### Quality Assurance/Quality Control:

-   Blind samples for analysis (i.e., field duplicates)
-   Triplicate analysis of standard solution

### Waste Disposal:

Most of the reagent solutions used in this procedure can go down the drain; however the pH should be near neutral (pH 5 -- 8). Flush during and after disposal by running tap water. Excess dry reagents from preparing the stock can go in the trash.

Consumables Ordering: Item Catalog \# Item Catalog \# Na2CO3 salt Fisher AA3648522 Buffer 3.557 (Ricca) Fisher 149816 Optima HCl (500 mL) Fisher A466500 Buffer 6.87 (Ricca) Fisher 154016

### Consumables Ordering:

|                     |                  |                      |               |
|------------------|------------------|-------------------|------------------|
| Item                | Catalog \#       | Item                 | Catalog \#    |
| Na~2~CO~3~ salt     | Fisher AA3648522 | Buffer 3.557 (Ricca) | Fisher 149816 |
| Optima HCl (500 mL) | Fisher A466500   | Buffer 6.87 (Ricca)  | Fisher 154016 |

## Preparing for Analysis

Remove samples for analysis from the fridge to allow them to warm up to room temperature prior to analysis.

Turn on the pH probe by pressing any key. Make sure it is reading in mV; if not, press 'MODE' until mV is being read. NOTE: put the meter on "Standby" after analysis

Prepare the pH probe for analysis. NOTE: follow these directions in reverse to store the pH probe after analysis

-   Remove the storage solution and parafilm from the probe
-   Check that there is enough liquid in the probe
-   Rinse the probe with MilliQ water from the squirt bottle and dab with a Kimwipe. NOTE: Do not rub the probe with a Kimwipe as this creates static.

Using the pH probe, measure the standard buffers (pH = 3.557 and 6.87) to create a calibration curve.

-   Place the pH probe in the buffer solution and allow the reading to stabilize. Record the millivolts (mV) on the sample data sheet.
-   Rinse off the pH probe with MilliQ water and dab dry with a Kimwipe
-   If the millivolts are not close to the values recorded below, the pH probe may be faulty or need recalibration. Consult with the lab manager before proceeding.

|               |                |
|---------------|----------------|
| **Buffer pH** | **millivolts** |
| 3.557         | 168            |
| 6.87          | -19            |

Make sure that all the sample cups and stir bars are clean and dry.

Turn on the electronic micropipette.

## Analysis of Standard

Place a sample cup with a microstir bar on the analytical balance. Tare the balance.

Pour and pipette 16 ± 0.1 mL of the 1000 µe/L standard into the sample cup on the balance. Remember, 16 mL = 16 g.

Record the mass of the standard sample on the standards data sheet.

Pour an aliquot of 0.5 N HCl into one of the plastic cups and cover with parafilm for storage. This will be the working acid solution you use for titrations and pre-dosing.

Pre-dose the standard sample with 0.2-0.4 mL of 0.5 N HCl acid. Remember, 100 µL = 0.1 mL

Place the standard sample on the stir plate and carefully position the pH probe so that is submerged in the sample without touching the sides or the microstir bar. Turn on the stir plate.

Using the electronic micropipette, add 0.01 mL aliquots of HCl until the meter reads 120 mV. Keep track of the volume added!

-   Record the pre-dosing volume and volume added in step 2.8 along with the mV reading on line 1.
-   Do not record any readings or volumes until the mV reading is greater than 120 mV.

Add an additional 0.01 mL aliquot of acid to the standard sample and let the pH reading stabilize. Record the new volume and mV.

Repeat this process for 10 total aliquots of 0.01 mL of acid. Record the volume and mV reading each time.

Cleaning up the standard sample:

-   Dump the sample down the sink.
-   Rinse off the pH probe with MilliQ water and dab dry with a Kimwipe

Repeat steps 2.1 -- 2.10 twice more for a total of three standard sample readings.

Compare the amount of acid added to reach 120 mV and the mV readings thereafter. If the standard samples are wildly different from each other, the pH probe or the standard solution may be compromised. Do not continue with sample analysis in this instance and seek guidance from the Lab Manager.

## Analysis of Samples

Follow the same procedure described in step 2.1 -- 2.10 above for each sample. **NOTE: the pre-dosing volume is different for each LTER lake.**

| Abbreviation   | Lake Name       | Pre-Dosing Volume |
|----------------|-----------------|-------------------|
| AL             | Allequash Lake  | 0.2 mL            |
| SP             | Sparkling       | 0.2 mL            |
| TR             | Trout Lake      | 0.2 mL            |
| BM             | Big Muskellunge | 0.1 mL            |
| CR             | Crystal lake    | None              |
| CB (Bog 27.2)  | Crystal Bog     | None              |
| TB (Bog 12.15) | Trout Bog       | None              |

: Northern Lakes Pre-Dosing

| Abbreviation | Lake Name | Pre-Dosing Volume |
|--------------|-----------|-------------------|
| FI           | Fish Lake | 0.7--0.9 mL       |
| WI           | Wingra    | 0.9--1.1 mL       |
| ME           | Mendota   | 0.9--1.1 mL       |
| MO           | Monona    | 0.9--1.1 mL       |
| WA           | Waubesa   | 0.9 mL            |
| KE           | Kegonsa   | 0.9 mL            |

: Southern Lakes Pre-Dosing


## Equations (testing)

$$ pH = {(mV-\ b_{std})\over m_{std}} $$

$$ F1 = 1000 \times {Volume Acid Added + Sample Volume \over Sample Volume} \times 10^{-pH} $$
