# Autoanalyzer Operating Instructions {#sec-autoanalyzer}

Start up:
 
NOTE: To save time, start a warm water bath to bring the reagents up to room temp. Takes about 15 minutes to get hot water and about 20 minutes to warm the reagents.
 
1) Hook up the appropriate analysis module to the colorimeter and the autosampler lines. Hook up bubble lines to air pumping lines on the peristaltic pump. Check the pump tubing diagrams in the Lab Methods Manual if you have any questions.
2) Place the appropriate pair of filters in the colorimeter. Only the colorimeter in the back will ever need to have the filters changed. The Nitrite/Nitrate module uses the 550 nm filter for both Nitrite/Nitrate and Total Nitrogen analyses. The Silica module uses the 660nm filters; the ammonia module uses the 630 nm filters; the phosphorus module uses the 880 nm filters.
3) Fill the Milli-Q reservoir 1/2 full with fresh Milli-Q water.
4) Check the waste carboy. Empty if it is 2/3 full.
5) Place the pump tubing reagent lines into MQ while the reagents are warming up. Place the sampler(probe) into the autosampler and let it run on MQ. Once the reagents have warmed up, move the lines from the MQ tothe appropriate reagent bottles (lines and bottles are labeled).
6) Turn on power switches at the outlet board. Be sure the autosampler's power button is not engaged.
7) Install the platen plate on the peristaltic pump assembly and run pump on high speed once to get reagents flowing through lines.
8) Check to see if all reagents are flowing smoothly through the pump lines. If not, change lines position on the pump rollers or replace worn pump tubing.
9) After the bubbles in the lines are flowing evenly and are uniform in size, turn on the colorimeter and plug in the heating element(when needed). Set STD. CAL. knob to value used on previous analyses.
10) After 15 minutes, turn on the strip chart recorder(s), and install the pen(s).
11) Use the baseline knob on the colorimeter to establish a zero baseline.
12) Once a stable baseline has been established(usually 45-60 minutes), place the prepared tray on the autosampler (a standard 1 and a Milli-Q sample should be run first for calibration purposes). Press down the autosampler power button.
13) When the calibration standard's peak comes through on the chart paper, adjust the STD. CAL. knob on the colorimeter to attain a peak height that is almost the full width of the chart paper at the peak's maxima. When the Milli-Q sample is being recorded, adjust the baseline knob of the colorimeter to place the recorder pen at its original zero position.
14) You now have the system calibrated and should not need to adjust the STD. CAL. knob the remainder of the analysis. If the baseline drifts up or down significantly over the course of the analysis, you may adjust it with the baseline knob when a Milli-Q sample is being detected. Record the adjustment with an arrow on the strip chart and label it with a message.
15) A full tray takes one hour and twenty minutes to be sampled completely. To assure that the autosampler stops at the end of the tray, place the red peg in the hole by the second-to-last sample cup. Continuous analysis may be maintained by taking the peg out and being sure to replace the sampled tray with an unsampled tray after the last sample has been aspirated.
16) Label the strip chart(s) with the name of the analysis, date, and analyst.
 
Shut down:
 
(Takes 30-40 minutes at end of analysis.)
0) Remove the cadmium column from the nitrate module without introducing any air into the column.
1) Remove reagent lines to a beaker filled with clean Milli-Q water. Run the pump on high speed one time. Place reagent bottles back in the walk-in cooler.
2) Remove the reagent lines to the small bottle half-filled with 0.1 N NaOH solution. Run the pump on high speed one time.
3) Remove the reagent lines to the beaker filled with Milli-Q water and run the pump one time on high speed.
4) Remove the reagent lines to a small bottle half-full of 0.1 N HCl. Run the pump on high speed one time.
5) Remove the reagent lines to the beaker of Milli-Q water and run the pump two or more times on high speed.
6) Remove the reagent lines to a plastic storage bag. Lift the autosampler "probe" out of the wash receptacle. Run the pump on high speed until liquid is no longer visible in the glass coils or the colorimeter tubing.
7) Remove the platen plate assembly and use a Kimwipe to clean the gray underside with isopropyl alcohol.
8) Turn off the power button on the autosampler and shut off all outlet power switches.
9) Turn off the power on the chart recorder and cap the recorder pen.
10) Check the waste carboy, empty if 2/3 full.
 
 
Additional Notes:
If you are having problems with an unsteady or unusual baseline, the pump tubing and/or the pumping action are suspect. Most problems encountered are due to irregularities in the pumping action from worn pump tubing or blockages/air leaks in the lines.
A level but noisy baseline may be caused by a small air bubble caught in the colorimeter's detection pathway. This may be "pulled through" by squeezing for a few seconds on the tube labelled TO PUMP and then releasing. A noisy baseline may also indicate worn pump tubing or a reagent which is precipitating.
If you notice that liquid is dripping from the connecting lines of the mixing module and the colorimeter, you have probably forgotten to add a detergent (Aerosol 22 or Brij 35) to your reagents. See the Lab Methods Manual for details.
 
Tray Preparation for NO2&NO3/NH4 and ∑N/∑P Analyses:
1) Fill tray with conical-bottomed cups
2) Fill each cup completely with 1 N HCl. (83 mls conc. HCl/L)
3) Aspirate the acid from each cup.
4) Fill each cup completely with fresh Milli-Q water.
5) Aspirate the Milli-Q water from each cup.
6) Repeat steps 4 and 5.
7) Aspirate thoroughly any water droplets in the bottom or clinging to the sides of the cups. This step is very important!
8) Fill sample tray immediately with the samples.
 
Tray Preparation for BRSi and DRSi analysis:
1) Fill tray with flat-bottomed cups.
2) Fill the sample tray with samples. (No washes or rinses are needed!)
 
last revision: 8/24/95 by James Thoyre