# Benthic Macroinvertebrates {#sec-benthicMacroinvertebrates}

### Purpose:

We sample for benthic macroinvertebrates in Trout, Crystal, and Sparkling lakes using Hester-Dendy samplers. We set samplers at four to six shoreline sites in 1 meter water depth, and at the deepest part of the lake. The same sampling sites are used every year. Three Dendy samplers per site are deployed for approximately one month beginning around the second week of August. Upon collection, we preserve the contents of each sampler in ethanol, and archive the samples in the Zoology museum.

### Sampling:

Dendies should be placed in the LTER lakes during the last week or immediately following the last week of the LTER fish sampling, and left in the lakes for approximately four weeks. Most of the dendies are set at fyke net sites so that both fish and macroinvertebrate data are collected there, as dendies can provide an indication of the species and biomass available as fish prey. Fish sampling and macrophyte sampling must be finished before dendies are set because their work disturbs the dendy sites.

Dendies were set in all the LTER lakes through 1989, and in 1992 and 1993. Only Trout, Crystal and Sparkling lakes were sampled in 1990, 1991, and 1994 to present.

#### Assembly 
Parts needed for one dendy sampler: 

- Six wide-meshed 3" x 3" vexar mesh squares 
- Four narrow-meshed 3" x 3" vexar mesh squares 
- Two 3" x 3" tempered hardboards 
- One 'choreboy' plastic scrubbing puff 
- One 5 inch long, 1/4" diameter eyebolt with nut 

Construct the dendy sampler by pushing the eyebolt through the center hole of each piece with the pieces fitting tightly on the bolt so the dendy cannot become compressed. The individual pieces are layered onto the bolt in this order: hardboard, five vexar meshes alternating wide with narrow, choreboy, five vexar meshes alternating wide with narrow, hardboard, nut. Fold the choreboy into three or four layers, with the most frayed end on the inside. The eyebolt should have a zip tie loop through it. Dendies should be assembled at the lab before going out to set them.

#### Placement in Lakes 
A "dendy set" consists of three dendy samplers from one lake site. In each set, the middle dendy is designated 'Dendy B' and the end dendies as dendies 'A' and 'C'. Dendy sets are placed in the lakes in one of three configurations. 

- Attached set with anchor and subsurface float. Most shoreline sites (also called fyke net sites) are set this way. Each set consists of a 6 meter line with a minnow trap clip at each end and one in the middle. A dendy is attached to each clip, with the middle clip also being attached to a brick anchor with subsurface float. Beginning 2010, the set in Crystal lake is anchored with a dog tieout stake pushed into the sediment. This is an attempt to reduce the migration of Dendies due to camper activity. 
- Unattached set with anchor and subsurface float. Shoreline sites in Sparkling Lakes are set this way. The individual dendies are not attached together. Each dendy has its own anchor, but only the middle dendy has a float. Setting the dendies as unattached sets reduces disturbance and loss of samplers to the curious public on this high use lake. 
- Attached set with surface float and no anchor. Deep hole sites (also called gill net sites) and all bog sites are set this way. Dendies are connected with a 6 meter line as for the shoreline sets, but are not anchored. The three dendies sink at a more equal rate if one of them is not weighted, hopefully coming to rest apart from one another rather than clumped together. Also, an anchor may pull the dendies into the bottom sediments. 

Shoreline sets are placed parallel to shore in about one meter of water. The floats are 250ml or 500ml plastic bottles partially filled with water so that they remain submerged.

Floats should be attached directly to the brick anchors rather than to the dendy or they will pull the dendy off the lake bottom. Floats should be labeled with 'Trout Lake Station' and our phone number. Sets are assembled in the boat and simply tossed over the side at the site. They should be set so that the dendies are spread out the length of the attachment line rather than clumped together. The samplers do not have to be upright.

#### Retrieval 

- Dendy sets remain in the lakes for about four weeks. Select a calm day for retrieval as the dendies and subsurface floats are very hard to see if there are even moderate waves on the lake. 
- Two people make up the retrieval crew: a 'boat person' and a snorkeler. Anchor the boat near the middle dendy, but collect dendies A and C before dendy B. Lying on your belly on the lake bottom, quickly place a dendy in its labeled freezer container, cover with lid, and return it to the boat person. Disturb it as little as possible before getting it contained, and be careful not to drag the other dendies when returning with it to the boat. 
- Due to physical limitations, the deep sites (and bog sites if sampled) are retrieved without snorkeling. Slowly pull the dendies up until they are within reach of the boat person. Place the container in the lake beneath the dendy and lift the dendy from the water with the container. 
- Unclip the line from the dendy, replace the container lid with a mesh panel lid, and drain the lake water from the container. Rinse the mesh lid into the container with 95% ethanol, filling the container about half full with EtOH. Cover the container, tilting and swirling it to immerse all the invertebrates in ethanol. 
- At each site, note on the field sheet whether all dendies were recovered.

| Inventory Needed | TR  | CR  | SP  | Total |
|:-----------------|:----|:----|:----|:------|
| dendies          | 21  | 15  | 15  | 51    |
| brick anchors    | 6   | 0   | 12  | 18    |
| 6-meter lines    | 7   | 5   | 1   | 13    |
| floats           | 7   | 1   | 5   | 13    |

### Equipment list for fieldwork

#### Setting:

-   dendies, lines, floats, brick anchors
-   Extras of all parts
-   Maps, data sheets, pencils, sharpee, string, scissors, duct tape

#### Retreival

-   dendy containers w/ lids, big gray transport tubs
-   Mesh strainer lids, 95% EtOH in gallon jugs, EtOH wash bottle
-   Foam board to wrap lines on
-   Maps and data sheets, pencils, sharpee, labeling tape, scissors
-   Anchor for boat, snorkeling gear (plenty of weight)
-   Hook to retrieve dendies set or moved into too deep water

### Processing

-   Dendies should be processed as soon as possible after collection to avoid desiccation due to evaporation of the ethanol. The freezer container lids do not fit tightly enough to allow long term storage in these containers. Do not allow the samples to freeze; store them in the garage storage room or the gear room if freezing nights are a possibility.
-   Assemble the Dandy Dendy Concentrator (DDC) so the stopper can be removed without crushing any organisms and the drain will flow into the sink. Rinse the DDC thoroughly with tap water. Make sure the stopper is in place, and place a clean beaker or 60 ml sample jar under the insect spout to catch any leaks.
-   Rinse the freezer container lid into the DDC with tap water. Transfer the dendy from the freezer container to a clean two-gallon bucket. The ethanol left in the freezer container can be poured into the DDC now or later. If there is a lot of particulate matter in the ethanol, wait till later to avoid clogging the mesh. Disassemble the dendy over the bucket, rinsing the vexar mesh squares, hardboards, and eyebolt into the bucket under running tap water. Place the mesh, hardboards, and eyebolt into a sample tray or dishpan. Leave the choreboy in the bucket to soak.
-   Using a fine tipped forceps, pick all matter from the mesh pieces, hardboards, and eyebolt, placing it into the DDC. Pick everything even if you don't know what it is, or are sure it's not animal. Rinse all dendy parts again into the bucket, scraping the hardboard with a razor blade under running water. When everything but the choreboy has been picked clean and rinsed, remove the choreboy from the bucket and pour the rinse water through the DDC. Place the bucket below the tap and gently unfold the choreboy. Rinse thoroughly under running tap water, turning the choreboy inside out if the organisms don't rinse clean initially. Pick the choreboy clean with forceps. Pour the rinse water through the DDC and rinse the bucket, sample tray ,and freezer container into the DDC.
-   Wash down the sides of the DDC with tap water. If there is a large amount of material in the DDC, use the forceps to gently transfer some of it to the sample jar. Use 70% ethanol to rinse the rest of the material into the sample jar. Rinse the DDC stopper and drain spout thoroughly. Label the sample jar in pencil with lake, dendy site number and letter, date set and date retrieved. Also record this information on a lab form and place it in the Dendy 3-ring binder. Fill the sample jar to the neck with 70% ethanol and cap tightly. Store all dendy samples from the same year together in a cardboard record storage box labeled with 'Dendy' and collection year. Transfer the sample box to the Zoology museum in Madison.
-   Leave all dendy components out to dry, then store in plastic storage boxes. Hardboard pieces need to dry for a long time before storage to ensure they are dry throughout. Store the choreboys in a large plastic bag.

Note: To make 4L of 70% EtOH, mix 2950 ml 95%EtOH with 1050ml water.

#### Floating

The next step in the process would be to separate the plant material from the animal material. This is done by placing the picked material in a pan with a solution of sugar water, in which the animals will float and can be skimmed off the top for identification. Details of this procedure can be found in Anderson, R.O. A Modified Flotation Technique for Sorting Bottom Fauna Samples. Limnology and Oceanography. Vol. 4, pp. 223-225.

We do not float LTER samples at this time. They are stored as picked above.

### Sampling Locations:

#### Trout Lake

- \# 7 Three birch trees at water's edge with a fourth birch stump about 5 ft long hanging over the water, 15 ft. south of two maple (with a third broken-trunk of a maple). Set out approx. 75 feet. (Added in 1982)
- \# 17 Approx. 200 ft. north of the old public access clearing by a double pine tree, half of which is broken off (w/ woodpecker holes). Also near a small dead birch tree about 20 ft. high.
- \# 31 Set out from a 6 foot gap between 2 large clumps of cedar. Roughly the middle of the island shoreline, and just to the left (south) of the macrophyte site. (Added in 1982) (Description revised in 1993 to avoid the macrophyte site and make finding it easier.)
- \# 67 45 ft. from shore, just south of the tip of the point, halfway to middle of small cove. Set out from largest white birch tree.
- \# 50 Set out from west pine of the two large outstanding pines - note severe drop-off.
- **Pine broke off before retrieval in 1994.
- \# 56 120 ft. from shoreline. Out from farthest to the west of 3 huge white pines. (not sampled in 1982-83)
Deep Halfway between lab and Millers Island.
 
 
#### Allequash Lake

- \# 14 Set 100 ft. from shoreline, out from group of white birch hanging over the water. Stump and large rock to the left.
- \# 16 Set out from group of 3 white birch at shoreline; one birch uphill from two is broken and fallen between the two trunks.
- \# 32 Set near overhanging black spruce to the right of all the big rocks and to the left of the dead bog trees.

Deep Permanent sampling site.

- \# 40 Set to the left of the campsite, halfway between campsite and two overhanging birch trees, one dead and almost in water. (These birches are about 20 feet apart)
 
#### Sparkling Lake

- \# 1 Off the boat landing to the south, set far enough out of the way so as not to be too obvious.
Deep Permanent sampling site.
- \# 19 Set between the two fallen trees.
- \# 21 Set beneath large dead pine overhanging the water.
- \# 24 By the last dead tree snag along the east shore, south of wayside. Set about 2 ft. to the south of the snag.
 
#### Big Muskellunge Lake

- \# 82 Set 25 ft. from shore, out from a small birch tree near the water. 50 feet to the right is a large stump. Behind are several red pine.
- \# 59 To the right of picnic area. Set at big oak 10 ft. from shore. An opening six feet wide (path?) is immediately next to the oak.
Deep Permanent sampling site.
- \# 51 By a stand of pines near a big double birch tree with one trunk dead, set out 10 feet from shore.
- \# 43 Set out from dead log lying horizontal in the water, halfway between narrows and point to the south. There is a dead pine near the shore 40 feet to the right. (site redescribed in 1986 when no previous landmarks recognizable)
  
#### Crystal Lake

- \# 6 Set out from 2nd pathway near quad of birch, east of boat landing.
- \# 9 Set out from 5th pathway near a dead tree. One birch is immediately at left of path and four single birch are between paths 4 and 5.

Deep Permanent sampling site

- \# 27 Near the north edge of the west beach area. Set out from large single birch, which is 30 ft. to right of trio of birch and an oak.
- \# 43 Set out from two merging white pines (one trunk is smaller and behind larger one), near two small birch trees in a 'V'. (Campsite 27)
  
#### 27-2 (Crystal) Bog
 
#### 12-15 (Trout) Bog

- \# 2 Mid Lake
- \# 1 & - \# 3 Approx. 200 feet to either side of walkway into the bog.
 
