<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hilary Dugan">

<title>alkalinity</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">



<section id="sec-alkalinity" class="level1">
<h1>Alkalinity</h1>
<p>Revised: Grace Wilkinson, March 2023</p>
<section id="purpose" class="level3">
<h3 class="anchored" data-anchor-id="purpose">Purpose:</h3>
<p>This procedure describes the steps to potentiometrically titrate water samples with standardized hydrochloric acid to calculate alkalinity according to Andersen, 2002 and USGS National Field Manual for the Collection of Water-Quality Data. The units of alkalinity for this analysis are microequivalents of carbonate per liter.</p>
</section>
<section id="sample-holding-time" class="level3">
<h3 class="anchored" data-anchor-id="sample-holding-time">Sample Holding Time:</h3>
<p>≤ 14 days @ 4° C unpreserved</p>
</section>
<section id="materials-required-for-titration" class="level3">
<h3 class="anchored" data-anchor-id="materials-required-for-titration">Materials Required for Titration</h3>
<p>(see materials for regents in step 5):</p>
<ul>
<li>MilliQ water</li>
<li>0.05N Hydrochloric Acid</li>
<li>1000 ueq/L Sodium Carbonate standard</li>
<li>pH meter and probe</li>
<li>pH buffers</li>
<li>Analytical balance</li>
<li>P200 manual, adjustable pipette</li>
<li>P100 electronic, adjustable pipette</li>
<li>Pipet tips</li>
<li>Small, graduated cups for titration</li>
<li>Micro-stirbar</li>
<li>MilliQ squirt bottle</li>
<li>Kimwipes</li>
</ul>
</section>
<section id="glassware-preparation" class="level3">
<h3 class="anchored" data-anchor-id="glassware-preparation">Glassware Preparation:</h3>
<p>The glass jar to hold waste rinses and the graduated cups used for titration should be rinsed with DI water from the tap at the sink and set upside down to dry.</p>
</section>
<section id="personal-protective-equipment-waste-disposal" class="level3">
<h3 class="anchored" data-anchor-id="personal-protective-equipment-waste-disposal">Personal Protective Equipment / Waste Disposal:</h3>
<p>Nitrile gloves and eye protection should be worn while titrating. Always use chemical resistant gloves (not latex), safety glasses, lab coat, and a fume hood while using concentrated acids to prepare the 0.05N HCl. This is not only for your protection, but also to prevent contamination of samples. Proper personal protective equipment is always required for safety and contamination prevention.</p>
</section>
<section id="quality-assurancequality-control" class="level3">
<h3 class="anchored" data-anchor-id="quality-assurancequality-control">Quality Assurance/Quality Control:</h3>
<ul>
<li>Blind samples for analysis (i.e., field duplicates)</li>
<li>Triplicate analysis of standard solution</li>
</ul>
</section>
<section id="waste-disposal" class="level3">
<h3 class="anchored" data-anchor-id="waste-disposal">Waste Disposal:</h3>
<p>Most of the reagent solutions used in this procedure can go down the drain; however the pH should be near neutral (pH 5 – 8). Flush during and after disposal by running tap water. Excess dry reagents from preparing the stock can go in the trash.</p>
<p>Consumables Ordering: Item Catalog # Item Catalog # Na2CO3 salt Fisher AA3648522 Buffer 3.557 (Ricca) Fisher 149816 Optima HCl (500 mL) Fisher A466500 Buffer 6.87 (Ricca) Fisher 154016</p>
</section>
<section id="consumables-ordering" class="level3">
<h3 class="anchored" data-anchor-id="consumables-ordering">Consumables Ordering:</h3>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 23%">
<col style="width: 26%">
<col style="width: 23%">
</colgroup>
<tbody>
<tr class="odd">
<td>Item</td>
<td>Catalog #</td>
<td>Item</td>
<td>Catalog #</td>
</tr>
<tr class="even">
<td>Na<sub>2</sub>CO<sub>3</sub> salt</td>
<td>Fisher AA3648522</td>
<td>Buffer 3.557 (Ricca)</td>
<td>Fisher 149816</td>
</tr>
<tr class="odd">
<td>Optima HCl (500 mL)</td>
<td>Fisher A466500</td>
<td>Buffer 6.87 (Ricca)</td>
<td>Fisher 154016</td>
</tr>
</tbody>
</table>
</section>
<section id="preparing-for-analysis" class="level2">
<h2 class="anchored" data-anchor-id="preparing-for-analysis">Preparing for Analysis</h2>
<p>Remove samples for analysis from the fridge to allow them to warm up to room temperature prior to analysis.</p>
<p>Turn on the pH probe by pressing any key. Make sure it is reading in mV; if not, press ‘MODE’ until mV is being read. NOTE: put the meter on “Standby” after analysis</p>
<p>Prepare the pH probe for analysis. NOTE: follow these directions in reverse to store the pH probe after analysis</p>
<ul>
<li>Remove the storage solution and parafilm from the probe</li>
<li>Check that there is enough liquid in the probe</li>
<li>Rinse the probe with MilliQ water from the squirt bottle and dab with a Kimwipe. NOTE: Do not rub the probe with a Kimwipe as this creates static.</li>
</ul>
<p>Using the pH probe, measure the standard buffers (pH = 3.557 and 6.87) to create a calibration curve.</p>
<ul>
<li>Place the pH probe in the buffer solution and allow the reading to stabilize. Record the millivolts (mV) on the sample data sheet.</li>
<li>Rinse off the pH probe with MilliQ water and dab dry with a Kimwipe</li>
<li>If the millivolts are not close to the values recorded below, the pH probe may be faulty or need recalibration. Consult with the lab manager before proceeding.</li>
</ul>
<table class="table">
<tbody>
<tr class="odd">
<td><strong>Buffer pH</strong></td>
<td><strong>millivolts</strong></td>
</tr>
<tr class="even">
<td>3.557</td>
<td>168</td>
</tr>
<tr class="odd">
<td>6.87</td>
<td>-19</td>
</tr>
</tbody>
</table>
<p>Make sure that all the sample cups and stir bars are clean and dry.</p>
<p>Turn on the electronic micropipette.</p>
</section>
<section id="analysis-of-standard" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-standard">Analysis of Standard</h2>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>